#
# Makefile CPU / CUDA
#

#-----------------------------------------------------------------------------

all: filter

filter:	Makefile-filter
	make -f Makefile-filter

clean:
	make -f Makefile-filter clean
